version: '3'

services:

  mosquitto-broker:
    container_name: my-mosquitto-broker
    image: eclipse-mosquitto:2.0.12
    ports:
      - "1883:1883"
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${PWD}/data:/mosquitto/data
      - ${PWD}/log:/mosquitto/log
    restart: always

  iot-inventory-api:
    container_name: http-iot-inventory-api
    image: http_iot_inventory_api:0.1
    ports:
      - "7070:7070"
    volumes:
      - ${PWD}/test_conf.yaml:/app/conf.yaml
    restart: always
  
  data-fetcher:
    container_name: mqtt_data_fetcher
    image: mqtt_data_fetcher:0.1
    volumes:
      - ${PWD}/test_fetcher_conf.yaml:/app/fetcher_conf.yaml
    restart: always
